workshopapps/devopsnotepad.desktop

frontend_website/src/App.js, frontend_website/src/Pages/BestPractice/BestPractices.module.css, frontend_website/src/Pages/Features/Feature.module.css
Linear Ticket : 
Features Page: https://linear.app/team-sandpaper/issue/FRO-84/features-page
Best Practice Page: https://linear.app/team-sandpaper/issue/FRO-94/build-best-practices-page
=> Making changes Reviewed by my Designer

frontend_website/src/App.js
issue: someone commented out the prices page route in the app.js
status: fixed
=> Akpovbiyor / uncommented out the prices route in the  app.js

dekstop_frontend/src/Pages/add_server/Joined/Joined.jsx, dekstop_frontend/src/Pages/add_server/Modal/Modal.jsx, dekstop_frontend/src/Pages/notes/Note.jsx, dekstop_frontend/src/Pages/notes/Note.module.css
https://linear.app/team-sandpaper/issue/FRO-33/build-desktop-ui-notes
=> Michado2019 michado2019

dekstop_frontend/src/Pages/add_server/Modal/Modal.jsx
fixed the conflicts existing in modal.jsx
=> fixed conflict in pages/add_server/modal/modal.jsx

dekstop_frontend/src/App.jsx, dekstop_frontend/src/Components/SideNav/SideNav.jsx
Implemented the updated UI for the side nav bar
https://linear.app/team-opspad/issue/DES2-20/implement-the-updated-ui-for-the-side-nav-bar
=> Feat/des2 20 implement the updated UI for the side nav bar

dekstop_frontend/src/App.jsx, dekstop_frontend/src/Components/SideNav/SideNav.jsx
Modified server link
Linear ticket: 
https://linear.app/team-opspad/issue/DES2-20/implement-the-updated-ui-for-the-side-nav-bar
=> Feat/des2 20 implemention the updated UI for the side nav bar

dekstop_frontend/src/Pages/notes/Note.jsx, dekstop_frontend/src/Pages/notes/Note.module.css
https://linear.app/team-opspad/issue/DES2-9/implement-the-functionality-for-create-notes
https://linear.app/team-opspad/issue/DES2-10/implement-the-functionality-for-clearing-notes
https://linear.app/team-opspad/issue/DES2-8/implement-the-updated-ui-for-the-notes-tab
=> note functionalities modified

dekstop_frontend/src/Pages/notes/Note.jsx, dekstop_frontend/src/Pages/notes/Note.module.css
https://linear.app/team-opspad/issue/DES2-9/implement-the-functionality-for-create-notes
https://linear.app/team-opspad/issue/DES2-10/implement-the-functionality-for-clearing-notes
https://linear.app/team-opspad/issue/DES2-8/implement-the-updated-ui-for-the-notes-tab
=> Michado2019 michado2019 michado2019

backend/package-lock.json, backend/src/controllers/AuthController.js, backend/yarn.lock
Removed some faulty validation that was breaking the functionality
=> Fix on BAC-9 -- made updates to updateUserPassword function

backend/src/controllers/AuthController.js, backend/src/database/repositories/ResetTokenRepo.js
Made important changes to fix errors in changing user password after it has been forgotten
=> FIX on FEAT BAC-9: made fixes to update password function

frontend_website/package-lock.json, frontend_website/src/Pages/CareerPage/SignUp/ComingSoonModal.module.css, frontend_website/src/Pages/CareerPage/SignUp/SignUp.jsx, frontend_website/src/Pages/ComingSoon/Header/Header.jsx
Linear Ticket: https://linear.app/team-opspad/issue/FRO-42/implement-the-functionality-of-the-notify-me-buttons-of-the-opspad
=> Build the modal for the career Page 

backend/src/controllers/ContactUsController.js, backend/src/database/migrations/20221210052735_create-contact.js, backend/src/database/repositories/contactUsRepo.js, backend/src/routes/contactUsRoute.js, backend/src/routes/index.js, backend/src/routes/swaggerDocs.js, backend/src/services/contactUs/create.js, backend/src/utils/email/template/contactUs.handlebars, backend/src/validators/contactUsController.js, backend/src/validators/validationMsg.js
* User sends inquiry data about opspad product and services
* Data provided is being validated to ensure right data type
* On success, an email service is being triggered
* Copy of the inquiry is saved in the database
* A confirmation email is being sent to the user.
linear : https://linear.app/team-opspad/issue/BAC-20/contact-form
=> feat(BAC-20) Implement contact us endpoint with email confirmation functionality

frontend_website/src/store/UserContext.jsx
Optional rendering for addUserHandler
=> fix: bug fix for usercontext

frontend_website/src/App.js
Reverts workshopapps/devopsnotepad.desktop#331
=> Revert "fix: fix signup email verification error"

frontend_website/src/Pages/Login/Login.jsx, frontend_website/src/Pages/SignUp/SignUp.jsx
made changes to a request body.
=> stringified token req

frontend_website/src/Pages/ContactUs/ContactUs.js
Modified the onSubmit handler for the contact form
=> added post requset for contact form

backend/package-lock.json, backend/src/routes/swaggerDocs.js, backend/src/utils/email/template/removeUser.handlebars, backend/yarn.lock
* resend verification
* delete user account
=> Chore: updated swagger docs for new endpoints

backend/src/initialize.js
* changed the production url to point to api
=> Update: swagger setup

frontend_website/src/Pages/ContactUs/ContactUs.js, frontend_website/src/Pages/ContactUs/Schema/index.js
Removed phone number validation and added email validation
=> updated contact form schema

dekstop_frontend/src/Components/ServerCard/ServerCard.jsx, dekstop_frontend/src/Pages/Notification/AvailabilityNotification/AvailabilityNotification.jsx, dekstop_frontend/src/Pages/Notification/AvailabilityNotification/AvailabilityNotification.module.css, dekstop_frontend/src/Pages/Notification/Notification.jsx, dekstop_frontend/src/Pages/Notification/SimpleNotification/SimpleNotification.jsx
- changes name for server availability to server notifications
- changes server health to server status
=> updates server availability to server notifications

dekstop_frontend/src/Components/GlobalPassword/Auth.module.css, dekstop_frontend/src/Components/SideNav/SideNav.jsx
- click anywhere on add server button to route to add server
=> fix add server btn issue

dekstop_frontend/src/Components/SideNav/SideNav.jsx, dekstop_frontend/src/Components/SideNav/SideNav.module.css
=> chore: Made the side nav responsive

frontend_website/src/Component/Navigation/NavData.js, frontend_website/src/Component/Navigation/Navbar.js
=> made changes
